'use client'

import React, { useEffect, useState } from 'react'
import { Trash2, Globe, Clock, Sparkles, ChevronDown } from 'lucide-react'
import Link from 'next/link'

type Answer = {
  id: string
  question_text: string
  answer: string
  used_count: number
  page_url: string
  updated_at: string
}

export default function AnswersPage() {
  // MONETIZE: To gate this page, uncomment the import above and replace the `return` below with:
  // return <PaywallBanner feature="Answer Library" description="View and manage all the answers generated by AI across your job applications." />
  
  const [answers, setAnswers] = useState<Answer[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [searchQuery, setSearchQuery] = useState('')
  const [expandedIds, setExpandedIds] = useState<Set<string>>(new Set())

  useEffect(() => {
    fetchAnswers()
  }, [])

  async function fetchAnswers() {
    try {
      const res = await fetch('/api/answers')
      if (!res.ok) throw new Error('Failed to load answers')
      const data = await res.json()
      setAnswers(data.answers || [])
    } catch (err: any) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  async function handleDelete(id: string) {
    if (!confirm('Are you sure you want to delete this answer?')) return

    try {
      const res = await fetch(`/api/answers/${id}`, { method: 'DELETE' })
      if (!res.ok) throw new Error('Failed to delete answer')
      
      setAnswers((prev) => prev.filter((a) => a.id !== id))
    } catch (err) {
      alert('Could not delete answer. Please try again.')
    }
  }

  function toggleExpand(id: string) {
    const next = new Set(expandedIds)
    if (next.has(id)) next.delete(id)
    else next.add(id)
    setExpandedIds(next)
  }

  const filteredAnswers = answers.filter((a) =>
    a.question_text.toLowerCase().includes(searchQuery.toLowerCase()) || 
    a.answer.toLowerCase().includes(searchQuery.toLowerCase())
  )

  if (loading) {
    return (
      <div className="max-w-5xl space-y-8 animate-pulse">
        <div className="h-10 bg-white/5 rounded-lg w-48"></div>
        <div className="glass-tile h-[400px] w-full"></div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="max-w-4xl mx-auto text-center py-12">
        <div className="text-red-500 mb-2">Failed to load answers</div>
        <p className="text-gray-500 text-sm">{error}</p>
      </div>
    )
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-black text-white tracking-tight">Answer Library</h1>
          <p className="text-white/50 text-sm mt-2 font-medium">
            Browse and manage all answers generated by Job Hunt Easy.
          </p>
        </div>
        <div className="text-sm font-black text-indigo-400 bg-indigo-500/10 px-4 py-1 rounded-full uppercase tracking-widest">
          {answers.length} {answers.length === 1 ? 'answer' : 'answers'}
        </div>
      </div>

      {answers.length > 0 ? (
        <>
          {/* Search */}
          <div className="relative group">
            <input
              type="text"
              placeholder="Search by question or answer keywords..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full bg-white/5 px-6 py-4 rounded-2xl border border-white/10 focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-transparent placeholder:text-white/20 text-white transition-all"
            />
            <span className="absolute right-6 top-4 opacity-30 group-focus-within:opacity-100 transition-opacity">🔍</span>
          </div>

          {/* List */}
          <div className="space-y-4">
            {filteredAnswers.length === 0 ? (
              <div className="text-center py-12 glass-tile border-dashed">
                <p className="text-white/30 text-sm font-medium">No answers match your search.</p>
              </div>
            ) : (
              filteredAnswers.map((answer) => {
                const isExpanded = expandedIds.has(answer.id)
                return (
                  <div key={answer.id} className="glass-tile p-6">
                    <div className="flex items-start justify-between gap-6 mb-4">
                      <h3 className="font-bold text-white flex-1 leading-snug">
                        {answer.question_text}
                      </h3>
                      <div className="flex items-center gap-4 flex-shrink-0">
                        <span className="inline-flex items-center gap-1 bg-indigo-500/10 text-indigo-400 font-black px-3 py-1 rounded-full text-[10px] uppercase tracking-wider">
                          {answer.used_count}× used
                        </span>
                        <button
                          onClick={() => handleDelete(answer.id)}
                          className="text-white/20 hover:text-red-400 transition-colors"
                          title="Delete answer"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </div>

                    <div 
                      className={`text-sm text-white/70 cursor-pointer font-medium leading-relaxed ${!isExpanded ? 'line-clamp-3' : ''}`}
                      onClick={() => toggleExpand(answer.id)}
                    >
                      {answer.answer}
                    </div>
                    
                    {!isExpanded && answer.answer.length > 200 && (
                      <button 
                        onClick={() => toggleExpand(answer.id)}
                        className="text-xs font-bold text-indigo-400 mt-3 hover:text-indigo-300 focus:outline-none flex items-center gap-1"
                      >
                        Show more <ChevronDown className="w-3 h-3" />
                      </button>
                    )}

                    <div className="flex items-center gap-6 mt-6 pt-6 border-t border-white/5 text-[10px] font-black uppercase tracking-widest text-white/20">
                      {answer.page_url && (
                        <div className="flex items-center gap-2">
                          <Globe className="w-3.5 h-3.5" />
                          {new URL(answer.page_url).hostname}
                        </div>
                      )}
                      <div className="flex items-center gap-2">
                        <Clock className="w-3.5 h-3.5" />
                        Last used {new Date(answer.updated_at).toLocaleDateString()}
                      </div>
                    </div>
                  </div>
                )
              })
            )}
          </div>
        </>
      ) : (
        <div className="glass-tile p-16 text-center">
          <div className="w-20 h-20 bg-white/5 rounded-3xl flex items-center justify-center mx-auto mb-8">
            <Sparkles className="w-10 h-10 text-white/20" />
          </div>
          <h2 className="text-2xl font-black text-white mb-3">No answers yet</h2>
          <p className="text-white/40 max-w-sm mx-auto font-medium leading-relaxed">
            When you use Job Hunt Easy to answer questions on job applications, they&apos;ll appear here so you can review and manage them.
          </p>
        </div>
      )}
    </div>
  )
}
