'use client'

import React, { useEffect, useState } from 'react'
// import PaywallBanner from '@/components/PaywallBanner'

type Answer = {
  id: string
  question_text: string
  answer: string
  used_count: number
  page_url: string
  updated_at: string
}

export default function AnswersPage() {
  // MONETIZE: To gate this page, uncomment the import above and replace the `return` below with:
  // return <PaywallBanner feature="Answer Library" description="View and manage all the answers generated by AI across your job applications." />
  
  const [answers, setAnswers] = useState<Answer[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [searchQuery, setSearchQuery] = useState('')
  const [expandedIds, setExpandedIds] = useState<Set<string>>(new Set())

  useEffect(() => {
    fetchAnswers()
  }, [])

  async function fetchAnswers() {
    try {
      const res = await fetch('/api/answers')
      if (!res.ok) throw new Error('Failed to load answers')
      const data = await res.json()
      setAnswers(data.answers || [])
    } catch (err: any) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  async function handleDelete(id: string) {
    if (!confirm('Are you sure you want to delete this answer?')) return

    try {
      const res = await fetch(`/api/answers/${id}`, { method: 'DELETE' })
      if (!res.ok) throw new Error('Failed to delete answer')
      
      setAnswers((prev) => prev.filter((a) => a.id !== id))
    } catch (err) {
      alert('Could not delete answer. Please try again.')
    }
  }

  function toggleExpand(id: string) {
    const next = new Set(expandedIds)
    if (next.has(id)) next.delete(id)
    else next.add(id)
    setExpandedIds(next)
  }

  const filteredAnswers = answers.filter((a) =>
    a.question_text.toLowerCase().includes(searchQuery.toLowerCase()) || 
    a.answer.toLowerCase().includes(searchQuery.toLowerCase())
  )

  if (loading) {
    return (
      <div className="max-w-4xl mx-auto space-y-6">
        <h1 className="text-2xl font-bold text-gray-900">Answer Library</h1>
        <div className="animate-pulse space-y-4">
          <div className="h-10 bg-gray-100 rounded-lg w-full"></div>
          <div className="h-32 bg-gray-100 rounded-xl w-full"></div>
          <div className="h-32 bg-gray-100 rounded-xl w-full"></div>
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="max-w-4xl mx-auto text-center py-12">
        <div className="text-red-500 mb-2">Failed to load answers</div>
        <p className="text-gray-500 text-sm">{error}</p>
      </div>
    )
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Answer Library</h1>
          <p className="text-gray-500 text-sm mt-1">
            Browse and manage all answers generated by Fillr.
          </p>
        </div>
        <div className="text-sm font-medium text-indigo-600 bg-indigo-50 px-3 py-1 rounded-full">
          {answers.length} {answers.length === 1 ? 'answer' : 'answers'}
        </div>
      </div>

      {answers.length > 0 ? (
        <>
          {/* Search */}
          <div className="relative">
            <input
              type="text"
              placeholder="Search by question or answer keywords..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full px-4 py-3 rounded-xl border border-gray-200 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent placeholder:text-gray-400"
            />
            <span className="absolute right-4 top-3 text-lg">🔍</span>
          </div>

          {/* List */}
          <div className="space-y-4">
            {filteredAnswers.length === 0 ? (
              <div className="text-center py-12 bg-gray-50 rounded-xl border border-dashed border-gray-200">
                <p className="text-gray-500 text-sm">No answers match your search.</p>
              </div>
            ) : (
              filteredAnswers.map((answer) => {
                const isExpanded = expandedIds.has(answer.id)
                return (
                  <div key={answer.id} className="bg-white rounded-xl p-5 border border-gray-100 shadow-sm hover:shadow-md transition-shadow">
                    <div className="flex items-start justify-between gap-4 mb-3">
                      <h3 className="font-semibold text-gray-900 flex-1">
                        {answer.question_text}
                      </h3>
                      <div className="flex items-center gap-3 flex-shrink-0">
                        <span className="inline-flex items-center gap-1 bg-indigo-50 text-indigo-700 font-medium px-2 py-0.5 rounded-full text-xs">
                          {answer.used_count}× used
                        </span>
                        <button
                          onClick={() => handleDelete(answer.id)}
                          className="text-gray-400 hover:text-red-600 transition-colors"
                          title="Delete answer"
                        >
                          <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                          </svg>
                        </button>
                      </div>
                    </div>

                    <div 
                      className={`text-sm text-gray-600 cursor-pointer ${!isExpanded ? 'line-clamp-3' : ''}`}
                      onClick={() => toggleExpand(answer.id)}
                    >
                      {answer.answer}
                    </div>
                    
                    {!isExpanded && answer.answer.length > 200 && (
                      <button 
                        onClick={() => toggleExpand(answer.id)}
                        className="text-xs font-semibold text-indigo-600 mt-2 hover:underline focus:outline-none"
                      >
                        Show more
                      </button>
                    )}

                    <div className="flex items-center gap-3 mt-4 pt-4 border-t border-gray-50 text-xs text-gray-400">
                      {answer.page_url && (
                        <div className="flex items-center gap-1">
                          <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9" /></svg>
                          {new URL(answer.page_url).hostname}
                        </div>
                      )}
                      <div className="flex items-center gap-1">
                        <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                        Last used {new Date(answer.updated_at).toLocaleDateString()}
                      </div>
                    </div>
                  </div>
                )
              })
            )}
          </div>
        </>
      ) : (
        <div className="bg-white rounded-2xl p-12 text-center border border-gray-100 shadow-sm mt-8">
          <div className="w-16 h-16 bg-indigo-50 text-indigo-600 rounded-full flex items-center justify-center mx-auto text-2xl mb-4">
            ✦
          </div>
          <h2 className="text-xl font-bold text-gray-900 mb-2">No answers yet</h2>
          <p className="text-gray-500 max-w-sm mx-auto mb-6">
            When you use Fillr to answer questions on job applications, they'll appear here so you can review and manage them.
          </p>
        </div>
      )}
    </div>
  )
}
